/**
 * Validation rules for a redemption request. Pure — no database, no clock of
 * its own — so the awkward cases can be tested directly.
 */

/**
 * How far in the past a client timestamp may be.
 *
 * A redemption queued offline carries the time it actually happened, because
 * the café day boundary means a cup taken at 23:50 and synced at 08:00 belongs
 * to the PREVIOUS business day. Take the sync time instead and it silently
 * burns the member's next day.
 *
 * 48 hours covers a café whose wifi was out overnight and a phone left in a
 * drawer over a weekend. Beyond that, something is wrong enough to want a
 * human looking at it rather than a silent backdated write.
 */
export const MAX_BACKDATE_HOURS = 48;

/**
 * How far in the future a client timestamp may be.
 *
 * Phone clocks drift, and a shop tablet that has never seen the internet can
 * be minutes out. Two minutes absorbs ordinary skew without letting a client
 * jump forward past a time-of-day rule ("valid 6am to 11pm") by lying.
 */
export const MAX_CLOCK_SKEW_MINUTES = 2;

export type TimestampRejection =
  | "missing"
  | "unparseable"
  | "too_far_future"
  | "too_far_past";

export type TimestampResult =
  | { ok: true; at: Date }
  | { ok: false; reason: TimestampRejection };

/**
 * When did this redemption actually happen?
 *
 * Client-supplied and therefore not trusted, but also not ignorable — for a
 * queued offline redemption it is the only record of when the cup was handed
 * over. So it is accepted within a bounded window and rejected outside it.
 */
export function resolveRedemptionTime(
  clientCreatedAt: unknown,
  now: Date,
): TimestampResult {
  if (typeof clientCreatedAt !== "string" || clientCreatedAt === "") {
    return { ok: false, reason: "missing" };
  }

  const at = new Date(clientCreatedAt);
  if (Number.isNaN(at.getTime())) {
    return { ok: false, reason: "unparseable" };
  }

  const minutesAhead = (at.getTime() - now.getTime()) / 60_000;
  if (minutesAhead > MAX_CLOCK_SKEW_MINUTES) {
    return { ok: false, reason: "too_far_future" };
  }

  const hoursBehind = (now.getTime() - at.getTime()) / 3_600_000;
  if (hoursBehind > MAX_BACKDATE_HOURS) {
    return { ok: false, reason: "too_far_past" };
  }

  return { ok: true, at };
}

/**
 * uuid v4, generated by the client when the confirm screen mounts and reused
 * on every retry. This is what makes a double-tap on a laggy connection burn
 * one cup instead of two.
 *
 * Checked for shape only. The value is the client's to choose — the guarantee
 * comes from the unique constraint in the database, not from this.
 */
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isValidIdempotencyKey(key: unknown): key is string {
  return typeof key === "string" && UUID.test(key);
}

/**
 * Does the chosen drink match what the plan covers?
 *
 * An empty eligible_items list means the plan does not restrict items, so
 * anything goes — including nothing. A plan that DOES list items requires one
 * of them, because otherwise `eligible_items` is decoration.
 */
export function isItemAllowed(
  itemLabel: string | null,
  eligibleItems: string[],
): boolean {
  if (eligibleItems.length === 0) return true;
  if (!itemLabel) return false;
  return eligibleItems.includes(itemLabel);
}
